### ISSUE TITLE
For implementing unsupported methods (getParameterTypeName and getParameterClassName)

### ISSUE THREAD

**Issue by higuchi-daisuke** [tada/pljava#110]
Hi, All.

I would like to implement unsupported methods. 
Firstly, I want to implement following methods: 
- getParameterTypeName()
- getParameterClassName()

If above 2 methods are supported, following source code has no unsuported methods. 
pljava\src\main\java\org\postgresql\pljava\jdbc\SPIParameterMetaData.java

These are already implemented in pgjdbc, so we should implement in PL/Java too. 
If there is any specific reason why these methods are unsupported, please let me know. 

Regards,

**Comment by jcflack** [comment]
Hello,

Please accept my apology, for some reason I overlooked the e-mail in November when you opened this issue.

Offhand, I am not aware of any deep reason those methods are unimplemented. There are places in PL/Java's internal JDBC fork where less-heavily-used methods were unimplemented simply for reasons of effort.

As for the future of PL/Java's internal fork of JDBC, I've been in some conversations about striving to reduce code duplication by trying to use more of pgjdbc, only instantiating PL/Java versions of a few key classes. That is the direction I would like to go, rather than investing any more heavy effort in the internal fork.

But that goal is not near yet, so for now I have no objection to committing implementations of these two methods if you have a pull request for them.

Again, please forgive my delay in responding.

Regards,
-Chap

**Comment by thallgren** [comment]
One thing to bear in mind when considering replacing the internal JDBC is
that the current design minimizes data copying. With the current design of
pgjdbc, data must be streamed. That adds an extra overhead that is often
unnecessary when running in-process. This is the main reason for the code
duplication.

If the relevant parts of of pgjcbc could be made adaptable to avoid the
streaming, then it would be a big win of course.

- thomas

**Comment by higuchi-daisuke** [comment]
Thank you for response. 
I understand these feature might be supported if I implement. 
I do not implement now, but create a pull request soon. 

Regards, 
Daisuke
