### ISSUE TITLE
Disable URL cache

### ISSUE THREAD

**Issue by fab1an** [tada/pljava#112]
Right now installing jars like this doesn't always work, because java caches the outer JAR and even if the file is replaced, it won't read the newer version:

`select sqlj.install_jar('jar:file:outer.jar!/inner.jar', 'inner', false)`

Here is the background info: https://stackoverflow.com/questions/11569511/java-net-url-cache-when-reading-from-files

**Comment by jcflack** [comment]
Hi,

I had never thought to call `install_jar` on a jar inside a jar. :) I can see that the results might be unexpected.

I anticipate a number of changes to PL/Java's class loading between 1.5.x and the next major version; therefore I do not know if any change of this behavior is worth making in 1.5.x, and it may be too early right now to know what would be needed in the next major. Do you have an application need currently for this?

In general, `install_jar` is not expected to be a frequent operation. If you need to reinstall, and it is a nested jar, and caching interferes, you can surely avoid the cache by opening a new connection (simply `\c` in `psql`, for example).

If that would be adequate, perhaps this issue is best handled as a note in the documentation for `install_jar`.

What do you think?

**Comment by fab1an** [comment]
I agree.

I needed it because my application has about 25 dependent jars. I ended up writing a bashscript to unpack and load them.

**Comment by fab1an** [comment]
Reopening because of the note in the documentation.

**Comment by jcflack** [comment]
Added a note about this in the "SQL functions" page on the wiki.
