### ISSUE TITLE
bytea[] performance

### ISSUE THREAD

**Issue by fab1an** [tada/pljava#114]
Is there a way to return a byte array from java to postgresql without copying?

Would it be more performant to write the bytea into a (temporary) table, then read it from there?

**Comment by yazun** [comment]
You mean off-heap with direct memory handling in your java code?
otherwise byte[]<->bytea is supported, we use it daily.

**Comment by fab1an** [comment]
No, heap is ok. I'm refering to this: (https://github.com/tada/pljava/wiki/Using-jdbc)

> Clob/Blob types need more work. byte[] and String works fine for bytea/text respectively. A more > efficient mapping is planned where the actual array is not copied.

Does that mean an a byte[] that I create in Java is copied when returned to postgresql as bytea?

**Comment by jcflack** [comment]
Yes, one copy takes place when a Java `byte[]` return value becomes a PostgreSQL `bytea` on return from the function. Similarly, a copy is made when a `bytea` parameter is passed into a Java function.

That is the simplest way to manage the complexity arising from the different lifetimes of Java objects (garbage collected when Java sees no live references) and PostgreSQL objects (reclaimed when their memory contexts are exited).

In some of the implementation internals of PL/Java itself, there are elaborate measures taken for Java objects to track when their pg counterparts' memory contexts disappear, or vice versa, but these tactics are not used for ordinary user data passed between pg and Java.

Java 9 is going to have public API for accessing off-heap data, something that has been possible only unofficially in Java 8 and earlier. There may be some portions of PL/Java that will benefit, though again, I think the lowest-hanging fruit will be certain frequent operations internal to PL/Java itself, and not necessarily in passing user data between pg and Java.

One (relatively) recent take on the tradeoffs involved is [here][dzone].

[dzone]: https://dzone.com/articles/is-using-unsafe-really-about-speed-or-functionalit

With respect to `Clob`/`Blob` types needing more work, a more valuable improvement might be to allow them to actually stream (as the API suggests) for very large values, rather than the current behavior of holding entirely in memory. Same for SQLXML...

**Comment by fab1an** [comment]
I didn't know about the feature in Java 9, thank for the thorough answer.

**Comment by jcflack** [comment]
> What about my initial suggestion of having java write into a table, then read the table from a wrapper procedure?

Sorry I didn't reply earlier. There would definitely be _at least_ an in-memory copy involved in writing to the table, and possibly more on the PostgreSQL side. It is more complex than simply returning your `bytea`.

As the link I included earlier explains,

> Something which has really improved in processor design is how fast it can copy large blocks of data.

That's especially true for simple byte-oriented data, so your application falls into the best case. I would just return the value, and not worry much about the one in-memory copy.
