### ISSUE TITLE
Unable to build pljava without errors

### ISSUE THREAD

**Issue by fhrbek** [tada/pljava#132]
I'm trying to build pljava from source on a CentOS machine. Although the build looks good and reports SUCCESS, there are lots of errors in the build log during C compilation. I'm not sure if the build is healthy, although it "kind of works".

Error example:
```
[ERROR]   Size nBytes = elemSize * nElems;
[ERROR]   ^
[ERROR] In file included from /usr/include/pgsql/server/postgres.h:47:0,
[ERROR]                  from /root/pljava-dev/pljava/pljava-so/src/main/include/pljava/pljava.h:29,
[ERROR]                  from /root/pljava-dev/pljava/pljava-so/src/main/include/pljava/JNICalls.h:12,
[ERROR]                  from /root/pljava-dev/pljava/pljava-so/src/main/include/pljava/PgObject.h:12,
[ERROR]                  from /root/pljava-dev/pljava/pljava-so/src/main/include/pljava/PgObject_priv.h:12,
[ERROR]                  from /root/pljava-dev/pljava/pljava-so/src/main/include/pljava/type/Type_priv.h:12,
[ERROR]                  from /root/pljava-dev/pljava/pljava-so/src/main/c/type/Array.c:9:
```

Full log: https://gist.github.com/fhrbek/481abc63147ed0d6f52eb77bfa5c78cd

I can eventually provide a full VM image if it's not possible to reproduce the problem.

**Comment by jcflack** [comment]
Hi Filip,

Are you building with -Pwnosign to suppress the nuisance sign-conversion warnings from gcc?

If you do that, the only warnings left over should be the ones about certain cases of transaction callback not yet handled, as described in the release notes.

The .h files included from PostgreSQL itself lead to great numbers of sign-conversion warnings, which nobody sees when building PostgreSQL itself because it builds with sign-conversion warnings turned off. PostgreSQL upstream isn't likely to change the .h files to make the warnings go away, because it would require making the code less readable with lots of casts that serve no other purpose.
https://www.postgresql.org/message-id/22297.1496244978%40sss.pgh.pa.us

In PL/Java's case, those gcc warnings are all enabled by the Maven plugin used to do the building. I would have liked to make Maven automatically add the gcc-specific option to turn off sign-conversion warnings (just when it detects the compiler is gcc) but that turns out not easy to do in Maven. So there's the -Pwnosign option to give on the mvn command line. It's mentioned more than once in the build docs and at least once in the build tips on the wiki, but still issues keep getting opened about it.

The warnings look like errors because Maven puts [ERROR] at the front of any line from the compiler that doesn't have the word warning: in it. The sign-conversion warnings from gcc are four lines long with only the first line containing warning: so Maven labels all the remaining lines [ERROR]. That's also explained in the build docs.

I've recently noticed there are gcc-specific pragmas to suppress certain warnings, and maybe I should just bite the bullet and add those to PL/Java's sources, protected by #ifdef _GNUC_, because just documenting a mvn option doesn't seem to be working.

-Chap

**Comment by fhrbek** [comment]
@jcflack You're absolutely right, thanks. My bad, I should have read the wiki docs more carefully. With -Pwnosign everything works as expected so I believe my build is really sane. I'm closing this ticket as there's nothing to do.
