### ISSUE TITLE
Annotations doesn't support CREATE CONSTRAINT TRIGGER

### ISSUE THREAD

**Issue by pmichalek** [tada/pljava#138]
Hi,
I have prepared patch, that implemsnts annotations support for:
CREATE CONSTRAINT TRIGGER
NOT DEFERRABLE | DEFERRABLE
INITIALLY IMMEDIATE | INITIALLY DEFERRED

If it is possible, please apply.

Regards Petr

[pljava_annotation_trigger.patch.txt](https://github.com/tada/pljava/files/1787134/pljava_annotation_trigger.patch.txt)

**Comment by jcflack** [comment]
Thanks for the patch! There are a few things I would probably do a little differently:

1. Java can be a very verbose language; I try to plan the annotations to minimize that. I would not want to type `@Trigger(constraint=true, deferrable=Trigger.Deferrable.DEFERRABLE, initially=Trigger.Initially.INITIALLY_IMMEDIATE)`. (`import` can be used to make the annotation itself shorter, but thn there are the `import` statements to type.)

2. I like to have the `characterize` method check the same requirements described in the PostgreSQL docs, and report them at compile time with error message language similar to the docs. That would mean, for example, making sure that `constraint` is only combined with `called=AFTER` and `scope=ROW`, `initially` is only used with `deferrable`, etc. That means people can have multiple mistakes identified right away at compile time, instead of waiting to build a jar and see `install_jar` throw only the first error on each attempt.

3. It is good to add something in `pljava-examples` (`annotation/Triggers.java` is probably a sensible place) to serve as a demonstration and a test.

One less-verbose way to approach the design would be to have only `boolean deferrable() default false` and `boolean initiallyDeferred() default false`. The defaults are the same as the PostgreSQL defaults, but the `DDRProcessor` can tell whether the value was explicitly set, or omitted from the annotation and defaulted (a `TriggerImpl` property can have a setter method, and a setter method gets passed an `explicit` flag). I might not use a separate `constraint` attribute in the annotation at all, but just infer a constraint trigger is wanted whenever `deferrable` is explicitly set (to either true or false).

Another approach would be to have just one enum attribute, `constraint`, with values `IMMEDIATE`, `INITIALLY_IMMEDIATE`, `INITIALLY_DEFERRED`. Its Java default would be `IMMEDIATE` (reflecting the PostgreSQL default for deferrable), but again, if not explicitly given at all, it would mean a normal, non-constraint trigger, and any explicit value would mean a constraint trigger. Naturally, either `INITIALLY_...` value implies deferrable.

The more I think about it, the more I like that way. The two booleans would be a simple implementation, but would need to check and report nonsense combinations like non-deferrable and initially deferred. The one enum with three values only lets you say the things that make sense, which in my view is a good design property.

For completeness, it may be worthwhile to have `from` also (and `fromSchema`, as the _referenced table name_ can be qualified), even though the docs don't recommend it for general use.

I won't have time to do much this week. If you want to work on it, and you have a github account, you could create a pull request on a branch like `feature/REL1_5_STABLE/constrainttrigger`. I know PostgreSQL core prefers emailed patches, but pull requests have been the tradition for PL/Java.

Cheers,
-Chap

**Comment by pmichalek** [comment]
Hi, Chap,

please could you create a branch (feature/REL1_5_STABLE/constrainttrigger), it seems, that I have no permissions to do it.

Regards

**Comment by jcflack** [comment]
Hi,

I think the usual GitHub Way of Doing Things would be for you to click Fork and get your own clone of the project; then you can create a `feature/REL1_5_STABLE/constrainttrigger` there (based on the tip of `REL1_5_STABLE`), and push your commits there. When ready, you'd then use GitHub's UI to make a "pull request" (being sure to specify `REL1_5_STABLE` as the branch to pull into; by default, it might assume `master`, which would make for a very messy diff).

If that seems straightforward enough, that's been the usual practice for PL/Java in the past. If it seems too much of a pain, I can work with an emailed patch.

-Chap

**Comment by jcflack** [comment]
The requested support appears in PL/Java 1.5.1-BETA2, released today.
https://github.com/tada/pljava/releases/tag/V1_5_1b2

**Comment by jcflack** [comment]
Closing with release of 1.5.1.
