### ISSUE TITLE
Cannot set classpath for self created schemas

### ISSUE THREAD

**Issue by Wollwesen** [tada/pljava#154]
Hello,

I'm new to PostgreSQL and PL/Java. I've been able to deploy the Hello world example from https://tada.github.io/pljava/use/hello.html. However this only works in the public schema. When I try to set the classpath for another schema set_classpath returns successfully and creates an entry in sqlj.classpath_entry. But I don't see the functions in the schema (using pgAdmin 4) nor can I call the functions. Are any privileges or configurations required for this?

I've also noticed that the schema names must not contain capital letters or set_classpath will not find them. Is that intentional? Are there conventions that schemas in Postgres are all lowercase?

I'm using PostgreSQL 10 and PL/Java 1.5.1b1 on Windows 10, in case that matters.

Regards

**Comment by jcflack** [comment]
Hi,

I wonder if the documentation needs to be clearer about the difference between _declaring_ a function _in_ a schema, and setting a classpath _for_ a schema. They are different notions (though you do need to do both before a PL/Java function will work).

Like any function in PostgreSQL, a PL/Java function will be declared in some schema when you install it. The way the [hello world example][hwe] is written, it will install itself into `public`. That means SQL will find the function if you fully qualify it (`SELECT public.hello('world');`), or if you say just `SELECT hello('world')` and the `public` schema is on your PostgreSQL `search_path` (which it normally is).

If you want the function to be _declared_ in some other schema, you can move it after it has been declared (`ALTER FUNCTION hello(varchar) SET SCHEMA foo`), but if you ever remove and reinstall the jar, it will put itself back in `public`. If you want it always to be installed in some other schema, you can edit the code and add `schema="foo"` inside the `@Function` annotation, and recompile/rebuild the jar.

So, all of that was about what schema the function is declared in and how SQL finds it, all ordinary PostgreSQL stuff. But there is also a Java classpath. That only matters after SQL has found the function and tries to execute it. Java needs to know what jar(s) to look in for the necessary class(es).

So PL/Java will look to see if a classpath is set for whatever schema you declared the function in. If there isn't one, it will then look for a classpath on the schema `public`. So you can often get away with only setting the classpath for `public`. If you prefer, and you have declared the function in some other schema, you can set the classpath there.

So, if you give a query like

    SELECT hello('world');

and you get an error like

    ERROR:  function hello(unknown) does not exist
    HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

you are having an issue with SQL not finding the function declaration, maybe because the schema you declared it in is not on your PostgreSQL `search_path`. On the other hand, if you get a message like

    ERROR:  java.lang.ClassNotFoundException: com.example.proj.Hello

then SQL found the function all right, but the function could not find its Java class, and that means something is off in how you have set the Java classpath.

There is more about that [here][pscp], but as that's in a section called "developer notes" it's understandable if you didn't find it right off.

As for `set_classpath` only liking lowercase schema names, yes, that doesn't surprise me. The SQL standard says identifiers are case-insensitive unless you quote them (identifiers have a special kind of quoting, you use double quotes, not single quotes as you use for strings). If they're not quoted, according to the standard, they should be stored as all uppercase, but PostgreSQL has a long history of lowercasing them instead. So if you say `CREATE SCHEMA MySchema;` with no quotes, you really created one called `myschema`. SQL will continue to find it no matter how you capitalize it, but PL/Java won't.

If you say instead `CREATE SCHEMA "MySchema";` it will actually be called `MySchema` (and be a different schema from `myschema`, if you have both!) and then you would have to capitalize it that way for `set_classpath` to find it. The SQL rules make things kind of messy sometimes.

[hwe]: https://tada.github.io/pljava/use/hello.html
[pscp]: https://tada.github.io/pljava/develop/coercion.html#The_per-schema_class_path

**Comment by Wollwesen** [comment]
Thank you very much for the clarification. The part about `@Function` installing the functions in the public schema by default and the `schema="foo"` parameter is what I was missing.

**Comment by jcflack** [comment]
Happy to be of help. There is one thing that I misstated: when there is no `schema=` in `@Function`, that does not mean it explicitly declares the function in `public`. It means there is no explicit schema, so the function is declared in whichever schema is first in your `search_path` at the moment you call `install_jar` (which is _typically_ `public`).

If you had `schema="public"` in the annotation, then the function would be declared in `public` unconditionally.
