### ISSUE TITLE
i386 libjvm_location gets mangled as /usr/lib/jvm/java-8-openjdk-1/jre/lib/1/server/libjvm.so

### ISSUE THREAD

**Issue by ChristophBerg** [tada/pljava#176]
On Debian sid/i386, `-Dpljava.libjvmdefault=/usr/lib/jvm/java-8-openjdk-i386/jre/lib/i386/server/libjvm.so` gets mangled so the .so file is not found anymore:
```
+ mvn --batch-mode -Pwnosign -Dpgsql.pgconfig=/usr/lib/postgresql/10/bin/pg_config -Dpljava.libjvmdefault=/usr/lib/jvm/java-8-openjdk-i386/jre/lib/i386/server/libjvm.so clean install

[...]

# create extension pljava;
WARNUNG:  01000: Java virtual machine not yet loaded
DETAIL:  /usr/lib/jvm/java-8-openjdk-1/jre/lib/1/server/libjvm.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
TIP:  SET pljava.libjvm_location TO the correct path to the jvm library (libjvm.so or jvm.dll, etc.)
```
The problem does not occur on amd64 and ppc64el.

https://www.postgresql.org/message-id/20180916201808.GA30681%40msg.df7cb.de

**Comment by jcflack** [comment]
The string given to `pljava.libjvmdefault` is passed verbatim to the C compiler as the value of a macro defined on its command line, and the C code uses it as a static initializer, stringized with `CppAsString2`.

That was a thinko, because `CppAsString2` does not macro-expand its argument only once; it repeatedly rescans and expands any pieces of the string that turn out to match _any macro that may exist during the compilation_.

In this case, `i386` in the path got replaced by `1` because the build was for i386, and the toolchain likely defines that macro to be 1 automatically to indicate the architecture.

However, it will happen with any other macro that exists in postgres. If your Java runtime happened to live on the path `/usr/lib/TEXTOID/jre` then, sure enough, you'd get errors about `/usr/lib/25/jre`.

This issue is both simple to understand and aggravating to fix; it would be ideal if the C preprocessor allowed defining something like `CppAsString2` that would stop after the first level of macro expansion, but a review of the standard does not turn up any way of doing that.

The obvious alternative, for the build script to generate the proper C string-literal quoted form, pass that as the command-line macro definition, and use it directly in the C code without `CppAsString2`, is not at all tidy to implement in the mostly-declarative language of Maven and Ant. (And while I have high confidence that Maven and Java will pass such a string intact to the C compiler on Unix-like systems, it could turn out to be a rigorous test of [whether they also get the very different quoting rules for Windows right][wquot]. I hope they do.)

[wquot]: https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

I am working on this approach, but I cannot rule out possibly abandoning it if the implementation in Maven becomes ridiculously complex or if it turns out to expose command-line argument-passing bugs on selected (ahem) platforms. A fallback position could be to simply recommend an easy workaround for any rare cases where the default JVM path contains something that collides with a macro.

## Workaround

A simple workaround can be demonstrated with a small C program standing in for the PL/Java build process:

```C
#include <stdio.h>

#define CppAsString(s) #s
#define CppAsString2(s) CppAsString(s)

int
main(int argc, char **argv)
{
	printf("%s\n", CppAsString2(DEFAULTPATH));
}
```

```sh
$ gcc -Di386 -DDEFAULTPATH=/foo/i386/bar stringize.c
$ ./a.out
/foo/1/bar
```
Replace a character in the colliding token with its hexadecimal escape (digit `6` with `\x36`):

```sh
$ gcc -Di386 -DDEFAULTPATH=/foo/i38\\x36/bar stringize.c   # backslash doubled, for the shell
$ ./a.out
/foo/i386/bar
```

(First instinct might have been to replace the first character, `i` with `\x69` here, but in this case that will fail because the following 3 characters are also hex digits and would be seen by the compiler as part of the hex escape.)

**Comment by jcflack** [comment]
Ok, the `bug/REL1_5_STABLE/issue176` branch should fix this.

It adds another large gob of polyglot JavaRhinoNashoScript in the otherwise-declarative world of Maven, but it does build successfully for me in Oracle Java 8 (with Nashorn), Oracle Java 7 (with Rhino, and a good `rhino-js-engine`), and IcedTea-6 (with a flaky `rhino-js-engine`).

I would very much like someone to test building on Windows (MSVC, MinGW, or both)....

**Comment by ChristophBerg** [comment]
I have to admit that "another large gob of polyglot JavaRhinoNashoScript" made me first "wtf", then laugh. :)
I confirm that the fix works for i386 and doesn't break the other two architectures we have.

**Comment by ChristophBerg** [comment]
While pondering about some other PG extension, I stumbled over something I vaguely remembered from reading the original K&R C book some 20 years ago: C macro stringizing: https://gcc.gnu.org/onlinedocs/cpp/Stringizing.html

Wouldn't that fix the problem with PLJAVA_LIBJVMDEFAULT more elegantly? Or does that apply only to macro arguments, and not macros themselves?
