### ISSUE TITLE
pom.xml file need update.

### ISSUE THREAD

**Issue by ramujagini** [tada/pljava#207]
pom.xml file has to updated with below plugin config in build section.
as while making pljava for postgres 11 and above version it is failing to download the mentioned artifact.
Please fix it

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.19.1</version>
        <configuration>
          <useSystemClassLoader>false</useSystemClassLoader>
        </configuration>
      </plugin>

**Comment by jcflack** [comment]
Thank you for the report. Could you include some more information about your environment, or attach (not paste) `mvn -X` output that shows the failure?

I have just built 1.5.2 for postgres 11.2 in a pristine environment with empty maven repo, and did not see a failure.

**Comment by ramujagini** [comment]
Hi Chapman Flack,
Please find the logs which you have requested

[mvn-X.zip](https://github.com/tada/pljava/files/2951053/mvn-X.zip)

..

**Comment by jcflack** [comment]
Hello,

From the logs, I notice that you are using Maven 3.0.5. I can replicate the problem here with 3.0.4 (or a very similar problem: I get a Guice provision error, but on a different plugin, not surefire.

Do you have any way of trying with a more recent Maven version? I can build here with 3.3.3 and no problem.

I see that my version-compatibility page says that Maven versions back as far as 3.0.4 are usable, but that seems to be no longer the case, at least without a serious effort to find limit versions for all of the plugins (not only surefire, apparently). And Maven 3.2.5 would be the latest usable if you were trying to build with Java 6, but I see that you are using Java 8, so there should be no problem building with reasonably current Maven versions.

**Comment by jcflack** [comment]
Will treat this as a documentation bug against the 1.5 branch, as the underlying issue seems to be that the oldest Maven versions that were described as usable no longer are (because of plugin version incompatibilities that we haven't pinned down). As of today, Maven 3.2.5 does work to complete a build from an empty repository, and that should be the oldest Maven version anyone needs, even if building for some reason with Java 6.

Not treating as a bug for the 1.6 branch (though the original reporter was building 1.6) because other work there has bumped its earliest supported Maven version to 3.5.2 anyway (yes, really three five two, not a transposition of three two five).

**Comment by jcflack** [comment]
Documentation was updated for 1.5.6 release. Closing this issue.
