### ISSUE TITLE
Where the real PL/SQL examples?

### ISSUE THREAD

**Issue by ppKrauss** [tada/pljava#214]
Hi. It is about documentation. The main link about examples seems https://tada.github.io/pljava/pljava-examples/index.html
... that links to  https://github.com/tada/pljava/tree/master/pljava-examples/src/main/java/org/postgresql/pljava/example

... But there is no example.

**Comment by jcflack** [comment]
Hello,

Did you mean to say PL/Java instead of PL/SQL?

I am not sure I understand the question. When I click that second link, it takes me directly to a github folder listing, that begins with the `annotation`, `jdk7`, and `saxon` folders, followed by files like `AnyTest.java`, `BinaryColumnTest.java`, `HugeResultSet.java`, and so on.

Those all are examples. Are you seeing something different?

**Comment by ppKrauss** [comment]
Hi @jcflack , sorry, yes, PL/JAVA that is not "pure java" but PL/JAVA  in a SQL context... I was expecting to see usual PL/SQL encapsulation, something (for all examples) as 

```SQL
CREATE OR REPLACE FUNCTION helloworld()
  RETURNS "text" AS
    'com.mycompany.helloworld.HelloWorld.helloWorld'
LANGUAGE 'java' IMMUTABLE;  
```

**Comment by jcflack** [comment]
Ok, so you're looking for examples of the SQL commands to deploy Java functions into the database once you have developed them.

That can be done in a couple of ways. In one, you write a .ddr file by hand that contains the necessary SQL commands. That's the older way. There is an example of that. If you follow the github link you gave earlier, it takes you into the `pljava-examples/src/main/java/org/postgresql/pljava/example/` folder. That's where the example _Java_ code is, but you can also navigate a few levels up (to `pljava-examples/src/main`) to see there is a `resources` folder, and from there you can see `deployment/examples.ddr`). So that shows you what it was like in the old days, to write a .ddr file by hand.

You can also see plenty of examples of the newer way. If you start at the link you gave, and go down into the `annotation` folder you see there, you will see that none of those examples are mentioned in the hand-written .ddr file you looked at. They don't need to be, because those examples all have Java annotations like `@Function` on the things that need to be deployed into SQL, and using those annotations, PL/Java generates the .ddr file automatically.

A good place to start and see how that all works would be [the Hello, World example](https://tada.github.io/pljava/use/hello.html).

**Comment by ppKrauss** [comment]
Hi @jcflack, thanks to explain the "newer way" (!), a way to maintain big projects, and to see all functions in a Java IDE, seems perfect!

We can close the issue: my only suggestion is to cite  at README this "new vs old" dichotomy and add in the first explanations an explicit  link to the "old"... for "old users".

**Comment by ppKrauss** [comment]
(oops, sorry, it is not README, is the section "[Use of PL/Java, in a nutshell](https://tada.github.io/pljava/#Use_of_PLJava_in_a_nutshell)"  and similars)

**Comment by jcflack** [comment]
I'm glad that helped. Thanks for the followup.

I'll give some thought to altering the "nutshell" documentation. Of course it gives the most attention to the annotation-driven way, which is the main thing to introduce to new users. I'm not sure I want the "nutshell" section to spend words on the old harder way. But I noticed the link from there to the wiki page about deployment descriptors, which needs some editing anyway, and that page could certainly stand to mention that they can be written by hand or autogenerated.
