### ISSUE TITLE
Request help on backup and recovery a database with Pl / java stored procedures 

### ISSUE THREAD

**Issue by ingenieurbruno** [tada/pljava#24]
Hello,
I developed an application with PostgreSQL 9.0 as database and i use,  with stored procedures Pl / java (in windows xp os). everything went smoothly. But when I deployed this application in another machine (Windows Server 2008).
None of these stored procedures are running, they returned me the following error:

ERREUR:  Unable to find static method Rh.Groupe.f_save_groupe with signature (ILjava/lang/String;)I
ERREUR: Unable to find static method Parametrage.Ville.f_findAll_ville with signature ()Lorg/postgresql/pljava/ResultSetProvider;

I do everything but without success.

before recovering my database, I make the following configurations:
-  In postgreSQL 9.0 (postgresql.conf file)

#dynamic_library_path = '$libdir'(I did not set up because I put the pljava.dll file in lib )

pljava.classpath = 'C:\\Program Files\\PostgreSQL\\9.0\\lib\\pljava.jar;C:\\Program Files\\PostgreSQL\\9.0\\lib\\Mission.jar;C:\\Program Files\\PostgreSQL\\9.0\\lib\\lib\\postgresql-9.1-901.jdbc4.jar;'

custom_variable_classes = 'pljava'	

log_min_messages = info	

- PATH environment
JRE_HOME=  C:\Program Files\Java\jre7
path=  %JRE_HOME%\bin;%JRE_HOME%\bin\client

-  Installing my . Jar file in PostgreSQL 9.0
SELECT sqlj.install_jar('file:///Program Files/PostgreSQL/9.0/lib/Mission.jar', 'Mission ',  true);

SELECT sqlj.install_jar('file:///Program Files/PostgreSQL/9.0/lib/pljava.jar', 'pljava ',  true);

SELECT sqlj.set_classpath('public', 'Mission');
SELECT sqlj.set_classpath('sqlj', 'Mission');

But in the end I found that the content of table sqlj.typemap_entry  is empty .

Thank you for bring me your support

**Comment by jcflack** [comment]
Keeping this issue (of the original three) open as a reminder there could be better documentation of how to backup/restore, and maybe better error messages from classloading/method resolution.

From the details above, it does not appear the OP had a problem related to `typemap_entry`. It seems more likely that the proper jar entries were not found or the right methods could not be found within them. It would have been helpful to know what was in `jar_repository` and `jar_entry`. Looking at the code where that message is produced, it seems there must have been a class, but the method was not found. Perhaps there was a version mismatch in the classes loaded?

It is possible that the JNI `getStaticMethodID` method creates an exception that would contain additional information not currently included in the message PL/Java reports. If so, perhaps the message could be made more helpful.

**Comment by jcflack** [comment]
It appears the original reporter will not be back. There was probably not a PL/Java problem here, and it will be hard to get more information about the reporter's situation. Some response to the issues I can see may help future readers who see this ticket.

The `Unable to find static method` messages would have been accompanied by the details of the underlying Java exceptions, but those details would have gone to `stderr` directly, instead of through the PostgreSQL logging system. I am not sure (for Windows) how to view the messages that were printed to `stderr`, but it will be helpful in troubleshooting. Future developments in the logging infrastructure should improve this.

PL/Java itself was operating, ruling out problems with the dynamic library path or `pljava.classpath`. However, `pljava.classpath` only needed to have `pljava.jar` in it. The jdbc jar is not needed (for any purpose in PL/Java, unless the reporter specifically wrote Java code using it to open _other_ database connections), and the `Mission.jar` only needed to be installed with `sqlj.install_jar`, not to be in the `pljava.classpath` (which is only where PL/Java needs to find _its own_ code).

Conversely, `sqlj.install_jar` did not need to be done for `pljava.jar`, only for `Mission.jar`.

Those are minor misconfigurations that did not cause the reported problem, but clarifying them may save someone else a bit of time. Whatever was happening for the poster will not be known without more reported detail.

Therefore, closing.
