### ISSUE TITLE
the sqlj schema installation  of pl/java stored procédures

### ISSUE THREAD

**Issue by ingenieurbruno** [tada/pljava#25]
Hello,
During installation of pl / java in PostgreSQL,
I want to know when will the  tables of sqlj schema are filled,particularly ff table
sqlj.typemap_entry .

**Comment by jcflack** [comment]
Hello,

It has been a long time since you opened this issue, and I am sorry it did not receive a reply. I hope that you were ultimately able to get your application migrated?

Because you opened three similar issues, I will close two (this one and #26). In #24 you gave the most complete details of your situation, and for now I will leave that one open as a reminder that better documentation is still needed for that.

To answer this question for the record, I don't think you mentioned whether your application creates any special type mappings. If it does not, I believe nothing is inserted in `sqlj.typemap_entry`.

If you install the `pljava-examples` jar, I believe one entry is created, for `javatest.complextuple`.

Regards,
-Chap
