### ISSUE TITLE
Backup and Recovery  of the stored procedures Pl / Java

### ISSUE THREAD

**Issue by ingenieurbruno** [tada/pljava#26]
Hello,
I have an application that I developed with a PostgreSQL database 9.0, With Pl/Java stored procedures I want to know:
- what are the configurations to the target database
- How to backup restore
- how to load all  jar files in the target database
- how to execute stored procedures in the target database

Thank you for your contribution.

**Comment by jcflack** [comment]
Hello,

It has been a long time since you opened this issue, and I am sorry it did not receive a reply. I hope that you were ultimately able to get your application migrated?

Because you opened three similar issues, I will close two (this one and #25). In #24 you gave the most complete details of your situation, and for now I will leave that one open as a reminder that better documentation is still needed for that.

-Chap
