### ISSUE TITLE
1.5.5 segfaults on ppc64el with PG12

### ISSUE THREAD

**Issue by df7cb** [tada/pljava#277]
On ppc64el + PG12:

```
11:37:33 2020-06-03 09:37:33.903 UTC [9857] LOG:  server process (PID 9915) was terminated by signal 6: Aborted
11:37:33 2020-06-03 09:37:33.903 UTC [9857] DETAIL:  Failed process was running: SELECT sqlj.install_jar('file:/usr/share/postgresql/12/pljava/pljava-examples-1.5.5.jar', 'examples', true)
11:37:33 2020-06-03 09:37:33.903 UTC [9857] LOG:  terminating any other active server processes
```

PG9.5 .. PG11 are fine.

Full build log including very verbose debug info at https://pgdgbuild.dus.dg-i.net/view/Testsuite/job/postgresql-pljava-autopkgtest/23/architecture=ppc64el,distribution=sid/console

**Comment by jcflack** [comment]
Oh yuck. That's in some anonymous code blob made by PostgreSQL's JIT:

```
siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007fffde1f0000


Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007fff700010f4
C  [llvmjit.so+0x16958]
C  [regress: postgres postgres ::1(42910) SELECT+0x342a64]  ExecScan+0x444
```
I assume that's a JITed tuple-deforming routine. Will the build pass with `jit_tuple_deforming` turned off?

Will it pass with `jit_tuple_deforming` turned on but `jit_optimize_above_cost` set sky-high?

There are some recent backpatched fixes involving JNI references, on the branch `backpatch/REL1_5_STABLE/checkjni`. Does that work? (One can always hope.)

So this is PostgreSQL 12.3-1.pgdg+1? Was that a recent package update? Has this been succeeding since winter and only failing recently? Does the change coincide with updating the PostgreSQL package? Or the package supplying libLLVM maybe?

Would it be easy to start a debugger on that build of PostgreSQL and find out what lines of `ExecScan` are `ExecScan+0x444` and `ExecScan+0x208`?

Looks like `llvmjit.so` is also part of PostgreSQL; I wonder what line is `llvmjit.so+0x16958`. Basing the number just on the library name rather than a symbol looks ominous; does the PostgreSQL build include no symbols in `llvmjit.so` even when it includes them for core?

I found an online ppc64 disassembler at https://onlinedisassembler.com/odaweb/Iayg8bCo/0 - it has a lot of architecture-specific options and I don't know PowerPC well enough to be sure I have set them right. (I have to set it for **big**endian because of the way the Java error report groups the bytes in fours, which the online disassembler sees as words).

It looks plausible: with the value shown in `r2`, the `ld r4,-32768(r2)` produces the fault address.

```
   7fff70000ff4 e8 61 00 90   ld      r3,144(r1)
   7fff70000ff8 a0 83 00 06   lhz     r4,6(r3)
   7fff70000ffc 28 04 00 03   cmplwi  r4,3
   7fff70001000 40 80 00 14   bge-    0x7fff70001014
   7fff70001004 e8 61 00 90   ld      r3,144(r1)
   7fff70001008 38 80 00 03   li      r4,3
   7fff7000100c 48 00 1a c5   bl      0x7fff70002ad0
   7fff70001010 e8 41 00 18   ld      r2,24(r1)
   7fff70001014 e8 61 00 88   ld      r3,136(r1)
   7fff70001018 e8 83 00 00   ld      r4,0(r3)
   7fff7000101c e8 a1 00 80   ld      r5,128(r1)
   7fff70001020 88 c5 00 00   lbz     r6,0(r5)
   7fff70001024 e8 e1 00 78   ld      r7,120(r1)
   7fff70001028 f8 87 00 00   std     r4,0(r7)
   7fff7000102c e8 81 00 70   ld      r4,112(r1)
   7fff70001030 98 c4 00 00   stb     r6,0(r4)
   7fff70001034 e8 61 00 88   ld      r3,136(r1)
   7fff70001038 e8 83 00 08   ld      r4,8(r3)
   7fff7000103c e8 a1 00 80   ld      r5,128(r1)
   7fff70001040 88 c5 00 01   lbz     r6,1(r5)
   7fff70001044 e8 e1 00 78   ld      r7,120(r1)
   7fff70001048 f8 87 00 08   std     r4,8(r7)
   7fff7000104c e8 81 00 70   ld      r4,112(r1)
   7fff70001050 98 c4 00 01   stb     r6,1(r4)
   7fff70001054 e8 61 00 88   ld      r3,136(r1)
   7fff70001058 e8 83 00 10   ld      r4,16(r3)
   7fff7000105c e8 a1 00 80   ld      r5,128(r1)
   7fff70001060 88 c5 00 02   lbz     r6,2(r5)
   7fff70001064 e8 e1 00 78   ld      r7,120(r1)
   7fff70001068 f8 87 00 10   std     r4,16(r7)
   7fff7000106c e8 81 00 70   ld      r4,112(r1)
   7fff70001070 98 c4 00 02   stb     r6,2(r4)
   7fff70001074 38 60 01 00   li      r3,256
   7fff70001078 78 63 07 c6   rldicr  r3,r3,32,31
   7fff7000107c 64 63 3a 42   oris    r3,r3,14914
   7fff70001080 60 63 3a f8   ori     r3,r3,15096
   7fff70001084 38 80 01 00   li      r4,256
   7fff70001088 78 84 07 c6   rldicr  r4,r4,32,31
   7fff7000108c 64 84 3a 42   oris    r4,r4,14914
   7fff70001090 60 84 3a f0   ori     r4,r4,15088
   7fff70001094 e8 a1 00 88   ld      r5,136(r1)
   7fff70001098 e8 c5 00 10   ld      r6,16(r5)
   7fff7000109c e8 e1 00 80   ld      r7,128(r1)
   7fff700010a0 89 07 00 02   lbz     r8,2(r7)
   7fff700010a4 f8 c4 00 00   std     r6,0(r4)
   7fff700010a8 99 03 00 00   stb     r8,0(r3)
   7fff700010ac 38 60 01 00   li      r3,256
   7fff700010b0 78 63 07 c6   rldicr  r3,r3,32,31
   7fff700010b4 64 63 3a 42   oris    r3,r3,14914
   7fff700010b8 60 63 3b 08   ori     r3,r3,15112
   7fff700010bc 38 80 01 00   li      r4,256
   7fff700010c0 78 84 07 c6   rldicr  r4,r4,32,31
   7fff700010c4 64 84 3a 42   oris    r4,r4,14914
   7fff700010c8 60 84 3b 00   ori     r4,r4,15104
   7fff700010cc e8 a1 00 88   ld      r5,136(r1)
   7fff700010d0 e8 c5 00 08   ld      r6,8(r5)
   7fff700010d4 e8 e1 00 80   ld      r7,128(r1)
   7fff700010d8 89 07 00 01   lbz     r8,1(r7)
   7fff700010dc f8 c4 00 00   std     r6,0(r4)
   7fff700010e0 99 03 00 00   stb     r8,0(r3)
   7fff700010e4 38 60 01 00   li      r3,256
   7fff700010e8 78 63 07 c6   rldicr  r3,r3,32,31
   7fff700010ec 64 63 3a 42   oris    r3,r3,14914
   7fff700010f0 60 63 3a d0   ori     r3,r3,15056
-> 7fff700010f4 e8 82 80 00   ld      r4,-32768(r2)
   7fff700010f8 e8 84 00 00   ld      r4,0(r4)
   7fff700010fc 38 a0 00 00   li      r5,0
   7fff70001100 98 a3 00 1c   stb     r5,28(r3)
   7fff70001104 7c 43 13 78   mr      r3,r2
   7fff70001108 f8 61 00 18   std     r3,24(r1)
   7fff7000110c 38 60 01 00   li      r3,256
   7fff70001110 78 63 07 c6   rldicr  r3,r3,32,31
   7fff70001114 64 63 3a 42   oris    r3,r3,14914
   7fff70001118 60 63 3a d0   ori     r3,r3,15056
   7fff7000111c 7c 8c 23 78   mr      r12,r4
   7fff70001120 7c 89 03 a6   mtctr   r4
   7fff70001124 4e 80 04 21   bctrl
   7fff70001128 e8 41 00 18   ld      r2,24(r1)
   7fff7000112c 38 80 01 00   li      r4,256
   7fff70001130 78 84 07 c6   rldicr  r4,r4,32,31
   7fff70001134 64 84 3a 42   oris    r4,r4,14914
   7fff70001138 60 84 3a d0   ori     r4,r4,15056
   7fff7000113c 38 c0 01 00   li      r6,256
   7fff70001140 78 c6 07 c6   rldicr  r6,r6,32,31
   7fff70001144 64 c6 3a 42   oris    r6,r6,14914
   7fff70001148 60 c6 35 d5   ori     r6,r6,13781
   7fff7000114c 38 e0 01 00   li      r7,256
   7fff70001150 78 e7 07 c6   rldicr  r7,r7,32,31
   7fff70001154 64 e7 3a 42   oris    r7,r7,14914
   7fff70001158 60 e7 35 d8   ori     r7,r7,13784
   7fff7000115c 39 00 01 00   li      r8,256
   7fff70001160 79 08 07 c6   rldicr  r8,r8,32,31
   7fff70001164 65 08 3a 42   oris    r8,r8,14914
   7fff70001168 61 08 3a d0   ori     r8,r8,15056
   7fff7000116c 88 a8 00 1c   lbz     r5,28(r8)
   7fff70001170 f8 67 00 00   std     r3,0(r7)
   7fff70001174 98 a6 00 00   stb     r5,0(r6)
   7fff70001178 e8 61 00 a0   ld      r3,160(r1)
   7fff7000117c e8 63 00 00   ld      r3,0(r3)
   7fff70001180 e8 81 00 98   ld      r4,152(r1)
   7fff70001184 88 a4 00 00   lbz     r5,0(r4)
   7fff70001188 e8 c1 00 78   ld      r6,120(r1)
   7fff7000118c 38 e6 00 18   addi    r7,r6,24
   7fff70001190 e9 01 00 70   ld      r8,112(r1)
   7fff70001194 98 a8 00 03   stb     r5,3(r8)
   7fff70001198 7c a5 07 74   extsb   r5,r5
   7fff7000119c 2c 05 00 00   cmpwi   r5,0
   7fff700011a0 f8 61 00 68   std     r3,104(r1)
   7fff700011a4 f8 e1 00 60   std     r7,96(r1)
   7fff700011a8 40 82 00 18   bne-    0x7fff700011c0
   7fff700011ac e8 61 00 68   ld      r3,104(r1)
   7fff700011b0 48 00 19 79   bl      0x7fff70002b28
   7fff700011b4 e8 41 00 18   ld      r2,24(r1)
   7fff700011b8 e8 81 00 60   ld      r4,96(r1)
   7fff700011bc f8 64 00 00   std     r3,0(r4)
   7fff700011c0 e8 61 00 a0   ld      r3,160(r1)
   7fff700011c4 e8 63 00 00   ld      r3,0(r3)
   7fff700011c8 e8 81 00 98   ld      r4,152(r1)
   7fff700011cc 88 a4 00 00   lbz     r5,0(r4)
   7fff700011d0 54 a5 07 fe   clrlwi  r5,r5,31
   7fff700011d4 e8 c1 00 a8   ld      r6,168(r1)
   7fff700011d8 98 a6 00 00   stb     r5,0(r6)
   7fff700011dc 38 21 00 b0   addi    r1,r1,176
   7fff700011e0 e8 01 00 10   ld      r0,16(r1)
   7fff700011e4 7c 08 03 a6   mtlr    r0
   7fff700011e8 4e 80 00 20   blr
   7fff700011ec 00 00 00 00   .long 0x0
   7fff700011f0 00 00 00 00   .long 0x0
```

I kind of imagine tuple-deforming code might look like that. It would sure be nice to know more about what I'm looking at though.

I guess there is a `jit_dump_pitcode` that will dump the IR form of the generated routine. I've got no experience looking at LLVM IR either, but maybe there would be something useful in it.

I am not sure what `jit_debugging_support` actually does. "Register generated functions with GDB." Maybe that would give them names that would show up in the JVM-generated dump also? Who knows?

**Comment by jcflack** [comment]
Looks like the last test that passed was the issue192 test, so (judging by the order in the earlier jobs) it was working on the Unicode roundtrip. Kind of stands to reason, that one does enough work for JIT to get involved.

**Comment by jcflack** [comment]
You know, the SQL query that does that particular test is hairy enough in its own right (multiple CTEs of big tuples with array members and composite members with arrays in them too), I wonder if it is now doing double duty as a test case for PG 12's JIT tuple deforming.

```sql
WITH
 usable_codepoints ( cp ) AS (
  SELECT generate_series(1,x'd7ff'::int)
  UNION ALL
  SELECT generate_series(x'e000'::int,x'10ffff'::int)
 ),
 test_inputs ( groupnum, cparray, s ) AS (
  SELECT
    cp / 1024 AS groupnum,
    array_agg(cp ORDER BY cp), string_agg(chr(cp), '' ORDER BY cp)
  FROM usable_codepoints
  GROUP BY groupnum
 ),
 test_outputs AS (
  SELECT groupnum, cparray, s, unicodetest(s, cparray) AS roundtrip
  FROM test_inputs
 ),
 test_failures AS (
  SELECT *
  FROM test_outputs
  WHERE
   cparray != (roundtrip).cparray OR s != (roundtrip).s
   OR NOT (roundtrip).matched
 ),
 test_summary ( n_failing_groups, first_failing_group ) AS (
  SELECT count(*), min(groupnum) FROM test_failures
 )
SELECT
 CASE WHEN n_failing_groups > 0 THEN
  javatest.logmessage('WARNING', n_failing_groups ||
   ' 1k codepoint ranges had mismatches, first is block starting 0x' ||
   to_hex(1024 * first_failing_group))
 ELSE
  javatest.logmessage('INFO',
     'all Unicode codepoint ranges roundtripped successfully.')
 END
 FROM test_summary;
```

where the `unicodetest` function is declared as

```
CREATE OR REPLACE FUNCTION unicodetest(s character varying, ints integer[])
 RETURNS unicodetestrow;
```

and the `unicodetestrow` type is

```
CREATE TYPE unicodetestrow AS (matched boolean, cparray integer[], s text);
```

I would be curious to run that same query, but after defining the `unicodetest` function equivalently in some other PL instead of PL/Java, and see if the JITed tuple deformer still blows up.

Only I don't have easy access to a `ppc64le` environment.

What the function does is receive a `varchar` and an `int[]`, where the codepoints in the `varchar` should match exactly the ints in the `int[]`, and return a `unicodetestrow` containing a `matched` flag (whether the contents matched exactly as it saw them), a new `int[]` (made from the argument `varchar`, and a new `text` (made from the argument `int[]`).

**Comment by jcflack** [comment]
Hi Christoph,

I would like to make some progress on this bug, and it is going to be challenging for me as I don't have convenient access to a ppc64el platform for testing on. I don't want to burden you with finding the problem, but I wonder if some of the more-information questions I had above would be things you could answer? Or, do you have suggestions where I could get access of some sort to a debian/ppc64el environment?

I see that the build log took place on `pgdgbuild-ppc64el`. Is that something I might get a chance to run some tests on, if I asked the right people nicely enough?

**Comment by df7cb** [comment]
Am 11. Juni 2020 02:58:11 MESZ schrieb Chapman Flack <notifications@github.com>:
>Hi Christoph,
>
>I would like to make some progress on this bug, and it is going to be
>challenging for me as I don't have convenient access to a ppc64el
>platform for testing on. I don't want to burden you with finding the
>problem, but I wonder if some of the more-information questions I had
>above would be things you could answer? Or, do you have suggestions
>where I could get access of some sort to a debian/ppc64el environment?
>
>I see that the build log took place on `pgdgbuild-ppc64el`. Is that
>something I might get a chance to run some tests on, if I asked the
>right people nicely enough?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tada/pljava/issues/277#issuecomment-642342827

Hi, sorry that I just dumped that at you and then disappeared. I'm currently on vacation, so availability is hard to predict, but I think I can arrange access to that box for you. Hopefully tomorrow.

**Comment by jcflack** [comment]
> I assume that's a JITed tuple-deforming routine. Will the build pass with `jit_tuple_deforming` turned off?

No. It passes with `jit` turned off, but not with only `jit_tuple_deforming` turned off.

It does pass with only `jit_expressions` turned off.
 
> Will it pass with `jit_tuple_deforming` turned on but `jit_optimize_above_cost` set sky-high?

`explain` says it wasn't optimizing.

> Looks like the last test that passed was the issue192 test, so (judging by the order in the earlier
> jobs) it was working on the Unicode roundtrip. Kind of stands to reason, that one does enough
> work for JIT to get involved.

Setting `client_min_messages` to `debug2` shows indeed that is the test coming after issue192, and that query triggers PostgreSQL's first attempt to load the JIT provider. Loading of the JIT provider is accompanied by this message that I don't know the significance of:

```
ORC error: No callback manager available for powerpc64le-unknown-linux-gnu
```

Another effect of setting `client_min_messages` to `debug2` is it makes the test succeed.

I **hate** bugs like that.

No wait, it's worse. It has simply stopped failing for me. Even with the original settings. Even with PL/Java dropped and then in a fresh backend recreated. Even after a fresh `initdb`.

*Even after exiting and re-entering the chroot and reinstalling the packages.*

That is frustrating. I was reproducing it quite reliably and now I can't.

By setting `jit_above_cost` and `jit_inline_above_cost` to a low number like 100, I can cause the JIT provider to be loaded earlier, ahead of the first test. Still everything passes now.

**Comment by jcflack** [comment]
> There are some recent backpatched fixes involving JNI references, on the branch
> backpatch/REL1_5_STABLE/checkjni. Does that work? (One can always hope.)

That branch is merged, and I built the tip of REL1_5_STABLE, which now includes them, and it ran successfully.

Which would have pleased me earlier, but now seems quite inconclusive since I stopped being able to reproduce the problem with the existing package.

**Comment by jcflack** [comment]
> Would it be easy to start a debugger on that build of PostgreSQL and find out what lines
> of `ExecScan` are `ExecScan+0x444` and `ExecScan+0x208`?

```
(gdb) info line *(ExecScan + 0x444)
Line 307 of "./build/../src/include/executor/executor.h"
   starts at address 0x10a5a2a60 <ExecScan+1088>
   and ends at 0x10a5a2a68 <ExecScan+1096>.

(gdb) info line *(ExecScan + 0x208)
Line 133 of "./build/../src/backend/executor/execScan.c"
   starts at address 0x10a5a2818 <ExecScan+504>
   and ends at 0x10a5a2830 <ExecScan+528>.
```

That's `ExecEvalExprSwitchContext` and the last line of `ExecScanFetch` to get the next tuple.

I begin to suspect something to do with management of the `ecxt_per_tuple_memory` context, and perhaps memory pressure.

> Looks like llvmjit.so is also part of PostgreSQL; I wonder what line is `llvmjit.so+0x16958`.

```
(gdb) info sharedlibrary llvmjit.so
From                To                  Syms Read   Shared Object Library
0x00007fff6c0383e0  0x00007fff6c04e244  Yes         /usr/lib/postgresql/12/lib/llvmjit.so

(gdb) info line *(0x00007fff6c0383e0 + 0x16958)
No line number information available for address 0x7fff6c04ed38
```

**Comment by jcflack** [comment]
>Another effect of setting `client_min_messages` to `debug2` is it makes the test succeed.
> I **hate** bugs like that.

Right now it's failing repeatably again. And fails at `debug2`. The failure to fail yesterday was (I can hope) unrelated to `debug2` and just coincided with whatever had really changed to make the failures fail to happen.

At the moment, `free` shows (in case workload or memory pressure had something to do with it)

```
              total        used        free      shared  buff/cache   available
Mem:        8353024     1944512     4570688      260992     1837824     6080256
Swap:      52428736     1481920    50946816
```

**Comment by jcflack** [comment]
I am back to the can't-make-it-fail state again.

Am I running in some sort of container that adapts to resource usage and grows after some iterations?

Yesterday even exiting the chroot environment and entering again through `schroot` didn't help.

Is there something about the other workload on the box that changes at certain times?

**Comment by df7cb** [comment]
No containers involved. It would be nice if schroot had the ability to use namespaces of all sorts, but it doesn't have that, so all it does is to chroot and mount things. The only funky technology involved is that it uses overlayfs on tmpfs (backed by a huge swap partition).

**Comment by df7cb** [comment]
PG 9.5 up to PG 13 are fine now with 1.5.6, so I'm closing this.

**Comment by jcflack** [comment]
Thanks for the follow-up. I was never satisfied that I had found the specific cause, which makes me somewhat uneasy, but we do have Travis-CI building for PG12/Ubuntu/ppc64le now and [that is succeeding][ppcpg12]. It is building the `master` (upcoming 1.6) branch, but as of last night it has 1.5.6 merged up so it ought to detect most issues.

I notice the Travis build log shows the PostgreSQL server as [Ubuntu 12.4-1.pgdg18.04+1][ppcver], and that seems _not_ to have `--with-llvm` in the configuration. The issue did seem to be presenting within JIT code.

Looking at the corresponding Travis job for `x86_64`, I see what looks like the same server version [Ubuntu 12.4-1.pgdg18.04+1][x86ver], but that one _does_ report `--with-llvm` in its configuration.

Does that mean a PostgreSQL JIT issue was identified for `ppc64le` and the package is now being built without it? If so, I'll consider this truly closed and sleep better at night.

... or is the server package being built that way because of this?

[ppcpg12]: https://travis-ci.com/github/tada/pljava/jobs/394941653
[ppcver]: https://travis-ci.com/github/tada/pljava/jobs/394941653#L367
[x86ver]: https://travis-ci.com/github/tada/pljava/jobs/394941647#L371

**Comment by df7cb** [comment]
(Just for my understanding, I guess there's a "not" missing in the second sentence?)

Right, on stretch|bionic|xenial, llvm has been disabled on non-x86 because the the llvm version there is missing r328687. (I don't have the svn link here atm, Andres had pointed out that problem.)

I forgot the details, but iirc the problem was discovered around PostGIS.

**Comment by jcflack** [comment]
Hmm, maybe somewhat idiomatic. I would be happier if I had ever felt truly satisfied that I had pinpointed a cause. But I was not so successful.

It looks as if the r328687 discussion you refer to was [here][r328687]. The symptoms look somewhat different. But perhaps I will relax a bit anyway knowing that there may have been an issue elsewhere.

[r328687]: https://www.postgresql.org/message-id/20180523115900.GA28424%40msg.df7cb.de

**Comment by df7cb** [comment]
LLVM-specific issues are common, if that makes you sleep better: https://www.postgresql.org/message-id/20200925152907.GI293907%40msg.df7cb.de
