### ISSUE TITLE
falsey reasoning

### ISSUE THREAD

**Issue by ag-epam** [tada/pljava#337]
"because they are based on java.util.Date, which implies knowledge of a time zone" 
really? after this phrase all the rest of the stuff can be easily skipped

**Comment by jcflack** [comment]
Yes, `java.util.Date` is clearly described in Java's API docs as being an instant in time with an implicit zone (UTC, modulo some platform-dependent subtleties around leap seconds) and there is no serious argument to be made otherwise. Conversions between `java.util.Date` and other zoned representations involve calculating the zone difference, and conversions to/from non-zoned representations require a choice of zone to be assumed.

Closing and locking.
