### ISSUE TITLE
Please add Avain support

### ISSUE THREAD

**Issue by liuhuasong** [tada/pljava#34]
[Avain](http://oss.readytalk.com/avian/) is A lightweight alternative to Java, it's better than GCJ.

**Comment by jcflack** [comment]
Hmm, I have just looked at Avian, I see it does supply a [JNI][] implementation (without which this would be a _very_ impractical idea).

I should mention that PL/Java development has not targeted GCJ now for some time. The current PL/Java builds are tested with a conventional JVM using JNI.

Avian's [classpath documentation][acp] does not show the JDBC (`java.sql`) classes, which would be needed. The build instructions say that it can be [built to use the full class library from openjdk][ojk], but that this produces either a more conventional libjvm.so that loads classes from the filesystem at runtime, or a _very large_ standalone executable; perhaps that is not what you wanted by using Avian.

If, under those conditions, you would still see a great benefit to supporting Avian, it would probably be up to you or another strongly interested party to do the major part of the proof-of-concept development and demonstrating the advantages. I would be interested in the progress and results.

As far as being an issue for mainline PL/Java development, I think this can be closed.

[JNI]: https://github.com/ReadyTalk/avian/blob/master/src/jnienv.cpp
[acp]: http://oss.readytalk.com/avian-web/javadoc-1.2.0/index.html
[ojk]: https://github.com/ReadyTalk/avian/blob/master/README.md#user-content-building-with-the-openjdk-class-library
