### ISSUE TITLE
why can't I create a file in the pl/java?

### ISSUE THREAD

**Issue by dengpan1** [tada/pljava#380]
I tried to create a temporary file in the program, it could not be created, 
my code:
`File.createTempFile("tmp", ".txt");`

reported an error when I run it in the PostgreSQL:
> ERROR:  java.sql.SQLDataException: Unable to create temporary file

How do I create temporary files? please help me.

**Comment by jcflack** [comment]
Hello,

Can you please indicate the version of PL/Java?

Also, if you run the same test in a new session after

```
SET log_min_messages TO debug1;
```

you may capture a stacktrace into the server log that will contain more information. (This has to be done in a new session because the `log_min_messages` setting has to be made before PL/Java is loaded in the session.)

**Comment by jcflack** [comment]
Also, the output of the `psql` command `\sf` for your PL/Java function would be useful. If the name of the function is `foo`, then

```
\sf  foo
```
should show just how it was declared.

**Comment by dengpan1** [comment]
> Hello,
> 
> Can you please indicate the version of PL/Java?
> 
> Also, if you run the same test in a new session after
> 
> ```
> SET log_min_messages TO debug1;
> ```
> 
> you may capture a stacktrace into the server log that will contain more information. (This has to be done in a new session because the `log_min_messages` setting has to be made before PL/Java is loaded in the session.)

pl/java version: 1.6.3
java version: 11
PostgreSQL version:13

**Comment by jcflack** [comment]
Thank you, that is helpful. Have you had a chance to copy the `\sf` output yet?

`\sf` is a shortcut specific to `psql`. If you are not using `psql`, can you show the SQL that you used to declare your Java function? If you declared it using the `@Function` annotation in the Java source, can you post that?

**Comment by dengpan1** [comment]
> Thank you, that is helpful. Have you had a chance to copy the `\sf` output yet?
> 
> `\sf` is a shortcut specific to `psql`. If you are not using `psql`, can you show the SQL that you used to declare your Java function? If you declared it using the `@Function` annotation in the Java source, can you post that?

I'm using `@Function`, I just coded the test class:

`import java.io.File;
import org.postgresql.pljava.annotation.Function;

public class Hello {

	@Function
	 public static String hello(String toWhom) throws Exception { 
		File f = File.createTempFile("tmp", ".txt");
		return "test";
	} 
}
`

**Comment by jcflack** [comment]
Ok! When you use `@Function` without a [`trust=` element][trust], that element defaults to `SANDBOXED`, and will prevent your function from opening files.

Because this is PL/Java 1.6, you have a variety of options for doing what you want.

The simplest would be to simply change the annotation to `@Function(trust=UNSANDBOXED)`, and then PL/Java will not apply any file-access restrictions. (The underlying OS permissions will continue to apply.)

The "UNSANDBOXED" setting does not really mean there are no limits applied to the code. In fact, "SANDBOXED" and "UNSANDBOXED" apply pretty much exactly the same limits, with the *only* difference being that the "UNSANDBOXED" policy includes

```
    permission java.io.FilePermission
        "<<ALL FILES>>", "read,write,delete,readlink";
```

and the "SANDBOXED" policy does not.

If you did not want to give your function those broad permissions on all files, you could also edit the `pljava.policy` file and add a permission to the policy for `PLPrincipal$Sandboxed *`. For example, you could add something like:

```
    permission java.io.FilePermission "${java.io.tmpdir}/*", "read,write,delete";
```

and then you could create functions in the default "SANDBOXED" languge and they would still be able to use files in the temporary directory.

If you wanted only certain functions to be able to do that, you could go further and create a new [alias Java language][alias], such as `java_with_tempfiles`, and you could edit the policy file to grant the new permission only to that "language". Then you could use `@Function(language="java_with_tempfiles")` on the functions that will need that permission, and other functions will default to the "SANDBOXED" language and will not have it.

This page gives the details of [configuring permissions in PL/Java][cperms].

You will see an important note at the end of that page about Java changes coming (in versions after Java 17) that will require some of the details to eventually change.

[trust]: https://tada.github.io/pljava/pljava-api/apidocs/org.postgresql.pljava/org/postgresql/pljava/annotation/Function.html#trust()
[alias]: https://tada.github.io/pljava/pljava/apidocs/org.postgresql.pljava.internal/org/postgresql/pljava/management/Commands.html#alias_java_language
[cperms]: https://tada.github.io/pljava/use/policy.html

**Comment by dengpan1** [comment]
> 

Thank you for your answer. It is okay!

I just had another problem, (Sorry, I'm a green hand), I customize the classloader in a Java class, reported an error when I run it: 
`> ERROR:  java.sql.SQLSyntaxErrorException: access denied ("java.lang.RuntimePermission" "createClassLoader")`

Can't I create custom classloader in Java ?

**Comment by dengpan1** [comment]
> Ok! When you use `@Function` without a [`trust=` element](https://tada.github.io/pljava/pljava-api/apidocs/org.postgresql.pljava/org/postgresql/pljava/annotation/Function.html#trust()), that element defaults to `SANDBOXED`, and will prevent your function from opening files.
> 
> Because this is PL/Java 1.6, you have a variety of options for doing what you want.
> 
> The simplest would be to simply change the annotation to `@Function(trust=UNSANDBOXED)`, and then PL/Java will not apply any file-access restrictions. (The underlying OS permissions will continue to apply.)
> 
> The "UNSANDBOXED" setting does not really mean there are no limits applied to the code. In fact, "SANDBOXED" and "UNSANDBOXED" apply pretty much exactly the same limits, with the _only_ difference being that the "UNSANDBOXED" policy includes
> 
> ```
>     permission java.io.FilePermission
>         "<<ALL FILES>>", "read,write,delete,readlink";
> ```
> 
> and the "SANDBOXED" policy does not.
> 
> If you did not want to give your function those broad permissions on all files, you could also edit the `pljava.policy` file and add a permission to the policy for `PLPrincipal$Sandboxed *`. For example, you could add something like:
> 
> ```
>     permission java.io.FilePermission "${java.io.tmpdir}/*", "read,write,delete";
> ```
> 
> and then you could create functions in the default "SANDBOXED" languge and they would still be able to use files in the temporary directory.
> 
> If you wanted only certain functions to be able to do that, you could go further and create a new [alias Java language](https://tada.github.io/pljava/pljava/apidocs/org.postgresql.pljava.internal/org/postgresql/pljava/management/Commands.html#alias_java_language), such as `java_with_tempfiles`, and you could edit the policy file to grant the new permission only to that "language". Then you could use `@Function(language="java_with_tempfiles")` on the functions that will need that permission, and other functions will default to the "SANDBOXED" language and will not have it.
> 
> This page gives the details of [configuring permissions in PL/Java](https://tada.github.io/pljava/use/policy.html).
> 
> You will see an important note at the end of that page about Java changes coming (in versions after Java 17) that will require some of the details to eventually change.

Thank you for your answer. It is okay! I can now create the file.

I just had another problem, (Sorry, I'm a green hand), I customize the classloader in a Java class, reported an error when I run it:
> ERROR: java.sql.SQLSyntaxErrorException: access denied ("java.lang.RuntimePermission" "createClassLoader")

Can't I create custom classloader in Java ?

**Comment by jcflack** [comment]
For the `createClassLoader` permission, you have pretty much the same options described above for file access, except the first, simplest one isn't available (even `trust=UNSANDBOXED` does not grant `createClassLoader` by default).

So you will end up having to edit the `pljava.policy` file (you can also create a separate policy file and add it to the `pljava.policy_urls` database setting, if you prefer not to change the `pljava.policy` file from the distribution).

In the same ways described above, you could add the necessary permission to the "sandboxed" language, or to the "unsandboxed" language, or both, or you could create an alias language and grant the permission only to that, and use that alias in `@Function(language=...)` for only the specific function that needs to create a classloader.

With a permission like `createClassLoader`, it is very easy to create unintended vulnerabilities (or inadvertently break how PL/Java works), so I would recommend being careful to limit the permission to whatever specific function in your code actually needs it (and of course design that code with great care). It is good to review the "risks of allowing this permission" column [in the API docs][jlrtp].

[jlrtp]: https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/RuntimePermission.html

**Comment by dengpan1** [comment]
> For the `createClassLoader` permission, you have pretty much the same options described above for file access, except the first, simplest one isn't available (even `trust=UNSANDBOXED` does not grant `createClassLoader` by default).
> 
> So you will end up having to edit the `pljava.policy` file (you can also create a separate policy file and add it to the `pljava.policy_urls` database setting, if you prefer not to change the `pljava.policy` file from the distribution).
> 
> In the same ways described above, you could add the necessary permission to the "sandboxed" language, or to the "unsandboxed" language, or both, or you could create an alias language and grant the permission only to that, and use that alias in `@Function(language=...)` for only the specific function that needs to create a classloader.
> 
> With a permission like `createClassLoader`, it is very easy to create unintended vulnerabilities (or inadvertently break how PL/Java works), so I would recommend being careful to limit the permission to whatever specific function in your code actually needs it (and of course design that code with great care). It is good to review the "risks of allowing this permission" column [in the API docs](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/RuntimePermission.html).

so cool,  I edited pljava.policy, do I have to recompile it?  Can I change it directly on the server?

**Comment by jcflack** [comment]
New sessions that start PL/Java will see the new policy file. An existing session that has already started PL/Java might not.

**Comment by dengpan1** [comment]
> 

Thank you very much for your help. now it's a success.

**Comment by dengpan1** [comment]
> New sessions that start PL/Java will see the new policy file. An existing session that has already started PL/Java might not.

Thank you very much for your help. now it's a success.
