### ISSUE TITLE
Estimation of per-session JVM total memory usage?

### ISSUE THREAD

**Issue by udesaiitrs** [tada/pljava#387]
Hi there, we are in the process of performance testing our implementation using PLJava, and have been trying to estimate TOTAL memory usage for each JVM instance, not just Heap memory usage. Has any testing been done for this on the PLJava team's end? The reason is because we are trying to understand how this will scale with 20 sessions (which could instantiate a JVM by using a pljava function), 40 sessions, etc. against a single PostgreSQL + TimescaleDB node. I'm using heap size of 32 MB as all of our functions require de-serialization of raw bytes.

vm_options: `-Xshare:auto -Xms32m -Xmx32m -Xss196k -XX:NativeMemoryTracking=summary -XX:+UseSerialGC`

I'm also running the PG/TS instance with 1 GB total memory on a Kubernetes cluster.

**Comment by jcflack** [comment]
Hi,

I assume you have looked at [this page][vmopts] already, right down to the "plausible settings" section toward the end. It has not been updated super-recently; in particular, the class-data sharing options have become more widely available and less proprietary in more recent Java releases.

The page refers to `visualvm` as a useful tool for examining the memory usage; it is sometimes a separate download now, though GraalVM community distributions include it.

There are, of course, several components to the memory usage: the Java heap, native memory allocated and managed by Java, and native memory allocated and managed by PostgreSQL. `-XX:NativeMemoryTracking` should tell you about the second category, but I doubt it will give you useful information about the third. I have not tried it. PostgreSQL's allocator statistics may be more useful there.

Typically, when PL/Java explicitly allocates native memory, it does so with PostgreSQL's allocator, so whatever native memory is being allocated and tracked by the Java allocator will probably be just what the JRE itself is using.

I think that's about all I can offer at the moment.

**Comment by udesaiitrs** [comment]
Can you give a little more detail into how I could dig deeper into the memory usage of the JVM via Postgres then? I tried some different java specific tools and nothing seems to work, including native memory tracking.  I'm running this in a kubernetes cluster and so it's a bit more difficult that when everything is run locally. Thanks!

**Comment by udesaiitrs** [comment]
Also, is there any documentation on the threading model of how PLJava works in the backend?

**Comment by jcflack** [comment]
The threading situation requires care, as you've already guessed, because PostgreSQL itself is strictly single-threaded.

In the documentation for [configuration variables][config], you can read about the `pljava.java_thread_pg_entry` setting. PL/Java on its own, or running its included examples/tests, will run successfully with the `throw` or `error` settings, showing that it does not _for its own part_ try to dive into PostgreSQL from more than one thread. (It once did, back when it used finalizers.)

Whether that is true of whatever Java code you will be running on it could be another story. You more or less need to decide which `java_thread_pg_entry` setting you are going to use, and take care that the code will behave as that setting requires. If there is substantial code that you didn't write, it might have to be tested with the `throw` or `error` setting to find out if it does or does not try to access PG from more than one thread.

[config]: https://tada.github.io/pljava/use/variables.html

**Comment by udesaiitrs** [comment]
Okay, I think I am following. I do not have deep Postgres/C knowledge, more of a Java programmer. If the way we are using PL/Java is just for static functions (such as take a string, make a change, return new string), and no direct querying of the database tables, then which would be the optimal setting? It seems that this setting will not really affect our use case here?

**Comment by udesaiitrs** [comment]
Further detail that may be helpful, we are storing a byte[] of a histogram object that we are writing PL/Java functions for that will de-serialize the histogram, return different statistical values, etc. So I want to understand if I can reduce garbage by re-using a ByteBuffer object.

**Comment by jcflack** [comment]
The `throw` setting should have the least overhead, if your application tests successfully with it and does not throw any `IllegalStateException` for "Attempt by non-initial thread to enter PostgreSQL from Java".

It might not be worth worrying about, though; the difference in overhead might be hard to measure, unless your functions themselves do a very small amount of work.

Do I correctly understand that you have some methods that take a `byte[]` parameter (and will be called from PostgreSQL passing something like a `bytea`) and your methods will deserialize that into some form and then return different values extracted from it?

And when you say "`byte[]` of a histogram object", do you mean in general some serialized form of histogram data, or do you mean specifically the Java serialized form of some `Serializable` Java object?

PL/Java will allocate a `byte[]` on each entry to the function; there isn't an easy way around that. But I believe Java's GC is already fairly well optimized for detecting and dealing with short-lived allocations. If the Java serialization mechanisms are involved, I might guess their overheads to be larger than that of the `byte[]`.

How large are the typical values, if I may ask? What sort of memory use and GC behavior are you seeing? Have you used, for example, `visualvm` to observe it?

**Comment by udesaiitrs** [comment]
Yes, we store https://github.com/tdunning/t-digest in byte[] form. I will try with the setting set to `throw`. 

Yes, for example one of our functions takes a double percentile, and a `byte[]` serialized tdigest parameter, deserializes into the Java object form, and returns the results of the `quantile()` function of the Java object. 

The `byte[]` values range from 250 bytes to 1kb+.

I have not been able to get visualvm to work with our setup. Running PG within a kubernetes cluster, I will give that another go now. 

We generally are only returning single values, but yes otherwise using the multiple `OUT` params would be ideal.

We also have a custom aggregation function that allows us to aggregate multiple histograms together based on time value, and so I have a custom aggregator function that also deserializes each `byte[]` histogram value and merges them, then re-serializes them.

**Comment by udesaiitrs** [comment]
Still no luck with `visualvm` w/kubernetes. If you have any pointers here that would be good. Thanks!

**Comment by jcflack** [comment]
I am not sure I would worry about the allocation of some ¼ to 1 kB byte arrays, but then I am not there.

Something you could consider would be to make a `t-digest` PostgreSQL [base type][baseudt]. You would need to develop a custom class, say `TDigestUDT` that implements `java.sql.SQLData`.

Its `readSQL` and `writeSQL` could use a length-prefixed form. If you had a statically-allocated `ByteBuffer` big enough for the biggest one you'll need, `writeSQL` could `asSmallBytes` the digest into that buffer, then `writeShort` the buffer's position, followed by `writeByte` for that many bytes of the buffer. For `readSQL`, do a `readShort` for the length, do that many `readByte` into a `ByteBuffer`, then pass the buffer to `fromBytes`. It's a lot of `readByte` method calls, but no extra allocations.

You could cut the `readByte` calls down by using `readLong` for as much of the size is divisible by 8 (careful with the buffer's byte order). That's about the most optimization possible; in particular (if allocation concerns you), don't be tempted by `readBinaryStream`: its PL/Java implementation pre-reads into a fresh allocation (I just checked).

I'm not sure what the effect on your performance would be, but the code would look nice. Your custom aggregator would then just be a Java method with `TDigestUDT` parameters and a `TDigestUDT` return, for example.

[baseudt]: https://tada.github.io/pljava/pljava-api/apidocs/org.postgresql.pljava/org/postgresql/pljava/annotation/BaseUDT.html

**Comment by udesaiitrs** [comment]
Right, it doesn't seem like much. But we're building a time series platform and using the Timescale extension so we're processing anywhere from 500 to 100k records a second on the write side, and read side it will scale based on user/client numbers. So a single query could process ~10,000 records on a read? So I'm just trying to get a good understanding of how the Java process works under the hood here. 

The option you outlined was my next step if using a `ThreadLocal<Bytebuffer>` did not work or was not performant, which is why I was asking about the threading model. However, performance seems just fine with my current implementation without going as far as you describe. 

Does the JVM then also follow a single-thread model? 
Can I look at PL/Java source code as well to understand this better? If so, which part of the project specifically?
Does the JVM per-active connection stay running as long as that connection is active? 
Do you have any other tool suggestions to monitor the memory usage within kubernetes/docker environments? 

Thanks!

**Comment by jcflack** [comment]
> Does the JVM then also follow a single-thread model? Can I look at PL/Java source code as well to understand this better? If so, which part of the project specifically? Does the JVM per-active connection stay running as long as that connection is active? Do you have any other tool suggestions to monitor the memory usage within kubernetes/docker environments?

The JVM has several background threads of its own, plus your own thread or threads (at least your main one, and any other threads you create from it). It is generally up to you when, if, and how new threads are created in your code.

In PL/Java, there is a notion of "the PG thread'. You could read the [documentation of the `DualState` class][dualstate] for how that is defined, which depends in part on the `java_thread_pg_entry` setting.

For now, whenever PostgreSQL calls into a PL/Java function, that will happen on "the PG thread". If your code ever makes calls back into PostgreSQL, they will succeed if made on the same thread. They will fail if made on any other thread, unless `java_thread_pg_entry=allow`, in which case that thread temporarily becomes "the PG thread" until that call returns.

In simple cases, you don't have to do anything special, because if you are not intentionally creating other threads and delegating work to them, then your processing happens on the thread where you were called. If you use simple Java constructs like parallel streams, with the results returned on your original thread, and no calls to PostgreSQL from the intermediate operations, that's simple too.

For a future version, I would like to add one more choice of setting, `java_thread_pg_entry=serve`, where an incoming call from PostgreSQL gets dispatched to a worker thread, and while waiting for that result, "the PG thread" serves as a one-thread `ExecutorService` that can handle database requests from any thread during the processing of that request. But that setting does not exist in 1.6.

Yes, the first call to a PL/Java function within a single PostgreSQL session backend launches the JVM in that session and it remains alive for the rest of that session.

I am not sure what to suggest about the monitoring tools. As I understand it, the ones I am aware of (`jconsole`, `jhsdb`, `visualvm`) generally rely on the same protocols (Java Management Extensions, Java Attach API) to gather information from the JVM. If you are having difficulty with one of the tools getting it to attach in your environment, I would expect similar difficulty with the others. Or, to rephrase it optimistically, I would expect that once you can get the attachment difficulties resolved for any one of them, they might be resolved for all.

**Comment by udesaiitrs** [comment]
Hi, thanks for your very detailed response, it gives a lot more clarity for me for our implementation. I believe that we will generally always use a very simple implementation and won't need to worry about spawning new threads as well. 

I think that this helps greatly and if anything new arises, I will follow up again. Thank you again!
