### ISSUE TITLE
Failed to execute goal org.postgresql:pljava-pgxs:2-SNAPSHOT:scripted-goal

### ISSUE THREAD

**Issue by RahulSam92** [tada/pljava#414]
[INFO] PostgreSQL PL/Java ................................. SUCCESS [  0.882 s]
[INFO] PL/Java API ........................................ SUCCESS [  3.115 s]
[INFO] PL/Java backend Java code .......................... SUCCESS [  3.268 s]
[INFO] PL/Java PGXS ....................................... SUCCESS [  3.253 s]
[INFO] PL/Java backend native code ........................ FAILURE [  3.411 s]
[INFO] PL/Java Ant tasks .................................. SKIPPED
[INFO] PL/Java examples ................................... SKIPPED
[INFO] PL/Java packaging .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.009 s
[INFO] Finished at: 2022-11-12T18:46:50+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.postgresql:pljava-pgxs:2-SNAPSHOT:scripted-goal (build-shared-object) on project pljava-so: Compilation failed with exit code: 1 -> [Help 1]

**Comment by jcflack** [comment]
Hmm, the comment might be a bit harsh, but I confess it is better than mine, which was nonexistent. Sorry about that. Some of the ideas to use when seeing a message like that are covered here:

https://tada.github.io/pljava/build/build.html#Troubleshooting_the_build

In very many of the cases that get asked as issues or on stackoverflow, it turns out to be a matter of not having installed the devel package for postgresql. That can be performed by searching through the `[ERROR]`s in the build log to find the ones that are really errors (as the documentation linked above explains) and seeing references to some missing postgresql header file.

**Comment by jcflack** [comment]
Closed waiting on reporter ... looks like a case of not having the PostgreSQL devel package installed
