### ISSUE TITLE
pljava-so: TypeError: null is not an Object in <eval>

### ISSUE THREAD

**Issue by const1995** [tada/pljava#498]
Hello, everyone!
While compiling pljava I have error: 
Failed to execute goal org.postgresql:pljava-pgxs:1.6.7:scripted-goal (build-shared-object) on project pljava-so: TypeError: null is not an Object in <eval> at line number 315 -> [Help 1]
Environment:
OS Windows 10
PostgreSQL 16
pljava 1.6.7
maven 3.5.4
g++ 13.2.0
javac 21.0.2

How can I fix this bug?

**Comment by jcflack** [comment]
Hi!

This appears to be the same as #485, and the build script did not match your build environment to either `Windows MSVC` or `Windows MinGW`, and as a result there are no build rules selected (giving a null result, instead of something more helpful like a "no build rules matched" message).

Depending on whether you have installed PostgreSQL that was built with MSVC (like the EDB package) or built with MinGW, you can read the corresponding `probe` test in `pljava-so/pom.xml` to see why the probe did not match in your environment. It could, for example, be looking for an environment variable that isn't set.

**Comment by const1995** [comment]
You are absolutely right. I compiled pljava in vcvars64.bat utility from MSVC 2017
Thank you very much!
